```
    @Test
    fun bindingPhoneTest() {
        identityTable.delete().execute()
        val addIdentityResponse1 = restTemplate.postForEntity("/auth/addIdentity", null, IdentityResult::class.java)
        val tokens = addIdentityResponse1.headers[JwtAuthenticationConverter.JWT_TOKEN_KEY]
        val httpHeaders = getHttpHeaders(tokens?.get(0))
        // 1. 校验添加
        val params1 = BindingPhoneParam(phone = "18712345678", code = "123456")
        val httpEntity = HttpEntity(params1, httpHeaders)
        val bindingPhoneResponse1 =  restTemplate.postForEntity("/auth/bindingPhone", httpEntity, IdentityResult::class.java)
        Assertions.assertNotNull(bindingPhoneResponse1.body?.id)
        Assertions.assertEquals(false, bindingPhoneResponse1.body?.isDel)
        Assertions.assertEquals("18712345678", bindingPhoneResponse1.body?.phone)
        Assertions.assertEquals(true, bindingPhoneResponse1.body?.isEnabled)
        Assertions.assertNotNull(bindingPhoneResponse1.body?.createdAt)
        Assertions.assertNotNull(bindingPhoneResponse1.body?.updatedAt)
        val bindingPhoneResponse2 =  restTemplate.postForEntity("/auth/bindingPhone", params1, ExceptionResult::class.java)
        // 2 校验重复添加
        Assertions.assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, bindingPhoneResponse2.statusCode)
        Assertions.assertEquals(AppSpringUtil.getMessage("mrs.phone-already-exists"), bindingPhoneResponse2.body?.message)

        Assertions.assertEquals(KatoBusinessException::class.java.name,bindingPhoneResponse2.body?.exception)

    }
```